#!/bin/sh
# LOAD Build Script

FLAGS_NORMAL="$CFLAGS -DNDEBUG -Werror"                                                                                                                               
FLAGS_DEBUG="$CFLAGS -D_DEBUG -g -Werror"                                                                                                                                 
FLAGS_PROFILE="$CFLAGS -DNDEBUG -D_PROFILE -pg -Werror"                                                                                                               
FLAGS_LOG="$CFLAGS -DNDEBUG -DDPRNT -Werror"  

# Default is to do the all
case $1 in "" )
	./build NORMAL
	./build DEBUG
	./build PROFILE
	./build LOG
esac

echo -n "LOAD: "

# Normal Build
case $1 in normal | NORMAL ) 
	echo "NORMAL"
	mkdir normal
	cd normal
	make -f ../makefile.lin "FLAGS=${FLAGS_NORMAL}" DEST=load dp_LIB=dp2.a
esac

# Debugging Build
case $1 in debug | DEBUG ) 
	echo "DEBUG"
	mkdir debug
	cd debug
	make -f ../makefile.lin "FLAGS=${FLAGS_DEBUG}" DEST=loadd dp_LIB=dp2d.a
esac

# Profiling Build
case $1 in profile | PROFILE ) 
	echo "PROFILE"
	mkdir profile
	cd profile
	make -f ../makefile.lin "FLAGS=${FLAGS_PROFILE}" DEST=loadp dp_LIB=dp2p.a
esac

# Logging Build
case $1 in log | LOG ) 
	echo "LOG"
	mkdir log
	cd log
	make -f ../makefile.lin "FLAGS=${FLAGS_LOG}" DEST=loadl dp_LIB=dp2l.a
esac
